/* tslint:disable */
/* eslint-disable */
/**
 * Nursing API
 * API for Nursing App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessTokenResponse,
  ForgotPasswordRequest,
  HttpValidationProblemDetails,
  InfoRequest,
  InfoResponse,
  LoginRequest,
  RefreshRequest,
  RegisterRequest,
  ResendConfirmationEmailRequest,
  ResetPasswordRequest,
  TwoFactorRequest,
  TwoFactorResponse,
} from '../models/index';
import {
    AccessTokenResponseFromJSON,
    AccessTokenResponseToJSON,
    ForgotPasswordRequestFromJSON,
    ForgotPasswordRequestToJSON,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    InfoRequestFromJSON,
    InfoRequestToJSON,
    InfoResponseFromJSON,
    InfoResponseToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    ResendConfirmationEmailRequestFromJSON,
    ResendConfirmationEmailRequestToJSON,
    ResetPasswordRequestFromJSON,
    ResetPasswordRequestToJSON,
    TwoFactorRequestFromJSON,
    TwoFactorRequestToJSON,
    TwoFactorResponseFromJSON,
    TwoFactorResponseToJSON,
} from '../models/index';

export interface AuthForgotPasswordPostRequest {
    forgotPasswordRequest: ForgotPasswordRequest;
}

export interface AuthLoginPostRequest {
    loginRequest: LoginRequest;
    useCookies?: boolean;
    useSessionCookies?: boolean;
}

export interface AuthManage2faPostRequest {
    twoFactorRequest: TwoFactorRequest;
}

export interface AuthManageInfoPostRequest {
    infoRequest: InfoRequest;
}

export interface AuthRefreshPostRequest {
    refreshRequest: RefreshRequest;
}

export interface AuthRegisterPostRequest {
    registerRequest: RegisterRequest;
}

export interface AuthResendConfirmationEmailPostRequest {
    resendConfirmationEmailRequest: ResendConfirmationEmailRequest;
}

export interface AuthResetPasswordPostRequest {
    resetPasswordRequest: ResetPasswordRequest;
}

export interface MapIdentityApiAuthConfirmEmailRequest {
    userId: string;
    code: string;
    changedEmail?: string;
}

/**
 * 
 */
export class NursingAPIApi extends runtime.BaseAPI {

    /**
     */
    async authForgotPasswordPostRaw(requestParameters: AuthForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['forgotPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'forgotPasswordRequest',
                'Required parameter "forgotPasswordRequest" was null or undefined when calling authForgotPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/forgotPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgotPasswordRequestToJSON(requestParameters['forgotPasswordRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authForgotPasswordPost(requestParameters: AuthForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authForgotPasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['useCookies'] != null) {
            queryParameters['useCookies'] = requestParameters['useCookies'];
        }

        if (requestParameters['useSessionCookies'] != null) {
            queryParameters['useSessionCookies'] = requestParameters['useSessionCookies'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponse> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authManage2faPostRaw(requestParameters: AuthManage2faPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TwoFactorResponse>> {
        if (requestParameters['twoFactorRequest'] == null) {
            throw new runtime.RequiredError(
                'twoFactorRequest',
                'Required parameter "twoFactorRequest" was null or undefined when calling authManage2faPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/manage/2fa`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TwoFactorRequestToJSON(requestParameters['twoFactorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TwoFactorResponseFromJSON(jsonValue));
    }

    /**
     */
    async authManage2faPost(requestParameters: AuthManage2faPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TwoFactorResponse> {
        const response = await this.authManage2faPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authManageInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/manage/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoResponseFromJSON(jsonValue));
    }

    /**
     */
    async authManageInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfoResponse> {
        const response = await this.authManageInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async authManageInfoPostRaw(requestParameters: AuthManageInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfoResponse>> {
        if (requestParameters['infoRequest'] == null) {
            throw new runtime.RequiredError(
                'infoRequest',
                'Required parameter "infoRequest" was null or undefined when calling authManageInfoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/manage/info`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InfoRequestToJSON(requestParameters['infoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoResponseFromJSON(jsonValue));
    }

    /**
     */
    async authManageInfoPost(requestParameters: AuthManageInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfoResponse> {
        const response = await this.authManageInfoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authRefreshPostRaw(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponse>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling authRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async authRefreshPost(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponse> {
        const response = await this.authRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authRegisterPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async authResendConfirmationEmailPostRaw(requestParameters: AuthResendConfirmationEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['resendConfirmationEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'resendConfirmationEmailRequest',
                'Required parameter "resendConfirmationEmailRequest" was null or undefined when calling authResendConfirmationEmailPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/resendConfirmationEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendConfirmationEmailRequestToJSON(requestParameters['resendConfirmationEmailRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authResendConfirmationEmailPost(requestParameters: AuthResendConfirmationEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authResendConfirmationEmailPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async authResetPasswordPostRaw(requestParameters: AuthResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['resetPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordRequest',
                'Required parameter "resetPasswordRequest" was null or undefined when calling authResetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/resetPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordRequestToJSON(requestParameters['resetPasswordRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authResetPasswordPost(requestParameters: AuthResetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authResetPasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async mapIdentityApiAuthConfirmEmailRaw(requestParameters: MapIdentityApiAuthConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling mapIdentityApiAuthConfirmEmail().'
            );
        }

        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling mapIdentityApiAuthConfirmEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['changedEmail'] != null) {
            queryParameters['changedEmail'] = requestParameters['changedEmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/confirmEmail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async mapIdentityApiAuthConfirmEmail(requestParameters: MapIdentityApiAuthConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mapIdentityApiAuthConfirmEmailRaw(requestParameters, initOverrides);
    }

}
