/* tslint:disable */
/* eslint-disable */
/**
 * Nursing API
 * API for Nursing App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteViewModel
 */
export interface InviteViewModel {
    /**
     * 
     * @type {Array<string>}
     * @memberof InviteViewModel
     */
    users: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InviteViewModel
     */
    id?: string;
}

/**
 * Check if a given object implements the InviteViewModel interface.
 */
export function instanceOfInviteViewModel(value: object): value is InviteViewModel {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function InviteViewModelFromJSON(json: any): InviteViewModel {
    return InviteViewModelFromJSONTyped(json, false);
}

export function InviteViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function InviteViewModelToJSON(json: any): InviteViewModel {
    return InviteViewModelToJSONTyped(json, false);
}

export function InviteViewModelToJSONTyped(value?: InviteViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'],
        'id': value['id'],
    };
}

