/* tslint:disable */
/* eslint-disable */
/**
 * Nursing API
 * API for Nursing App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedingDto } from './FeedingDto';
import {
    FeedingDtoFromJSON,
    FeedingDtoFromJSONTyped,
    FeedingDtoToJSON,
    FeedingDtoToJSONTyped,
} from './FeedingDto';

/**
 * 
 * @export
 * @interface SyncModel
 */
export interface SyncModel {
    /**
     * 
     * @type {Date}
     * @memberof SyncModel
     */
    lastSync?: Date;
    /**
     * 
     * @type {Array<FeedingDto>}
     * @memberof SyncModel
     */
    feedings?: Array<FeedingDto>;
}

/**
 * Check if a given object implements the SyncModel interface.
 */
export function instanceOfSyncModel(value: object): value is SyncModel {
    return true;
}

export function SyncModelFromJSON(json: any): SyncModel {
    return SyncModelFromJSONTyped(json, false);
}

export function SyncModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncModel {
    if (json == null) {
        return json;
    }
    return {
        
        'lastSync': json['lastSync'] == null ? undefined : (new Date(json['lastSync'])),
        'feedings': json['feedings'] == null ? undefined : ((json['feedings'] as Array<any>).map(FeedingDtoFromJSON)),
    };
}

export function SyncModelToJSON(json: any): SyncModel {
    return SyncModelToJSONTyped(json, false);
}

export function SyncModelToJSONTyped(value?: SyncModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastSync': value['lastSync'] == null ? undefined : ((value['lastSync']).toISOString()),
        'feedings': value['feedings'] == null ? undefined : ((value['feedings'] as Array<any>).map(FeedingDtoToJSON)),
    };
}

