services:
  nursingdb:
    container_name: nursingdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
  nursingweb:
    container_name: nursingweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - nursingdb
networks:
  default:
    name: nursing
    external: true

